Rails3.1: add "require 'shoulda/rails'" at test/test_helper.rb.
$ rake test:units

/REDMINE-1/hg-workdir/redmine-rails3-bb/test/unit/project_test.rb:69:
  undefined method `should_validate_presence_of' for ProjectTest:Class (NoMethodError)

--HG--
branch : rails3-straight-20110625-hg-git
extra : transplant_source : %1B%604Xi%7F%3B%F7%29%1B%2A%90jn%A0V%B8%EA%A8%F7